name: Mariya Workflow

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Run Python Script
      run: python main.py

    - name: Say Hello
      run: echo "GitHub Actions setup complete!"
